[package]
name = "hrm-nrf52840"
version = "0.2.0"
authors = ["Tobias Breitwieser <tobias@breitwieser.biz>"]
edition = "2018"
exclude = [".gitignore", ".github"]
documentation = "https://docs.rs/hrm-rs"
keywords = ["no-std", "MAX30102", "embedded", "embedded-hal-driver", "examples"]
categories = ["embedded", "no-std"]
readme = "README.md"
description = "HRM calculation for MAX30102"
license = "Apache-2.0"
repository = "https://github.com/tarfu/hrm-rs"


[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[dependencies]

[dev-dependencies]
embedded-hal = "^0.2"
bit_field = "0.10.0"
cortex-m = "^0.6"
cortex-m-rt = "^0.6"
panic-semihosting = "^0.5"
cortex-m-semihosting = "0.3.5"
nrf52840-hal = "^0.8"
shared-bus = { version = "0.1.4", features = ["cortexm"] }
embedded-graphics = "0.5"
heapless = "0.4.0"
st7735-lcd = {version = "0.6.1", features = ["graphics"] }


